swagger: "2.0"
info:
  title: ""
  version: ""
basePath: /
paths:
  /metrics:
    get:
      operationId: PrometheusHandleFunc
  /sequence_generate:
    post:
      operationId: GetSequence
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
