// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: sql_query.proto

package sqlquery

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SqlQueryService_ExecuteQuery_FullMethodName = "/sqlquery.SqlQueryService/ExecuteQuery"
)

// SqlQueryServiceClient is the client API for SqlQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 使用bytes类型来传输json数据
type SqlQueryServiceClient interface {
	ExecuteQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type sqlQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSqlQueryServiceClient(cc grpc.ClientConnInterface) SqlQueryServiceClient {
	return &sqlQueryServiceClient{cc}
}

func (c *sqlQueryServiceClient) ExecuteQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, SqlQueryService_ExecuteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SqlQueryServiceServer is the server API for SqlQueryService service.
// All implementations must embed UnimplementedSqlQueryServiceServer
// for forward compatibility.
//
// 使用bytes类型来传输json数据
type SqlQueryServiceServer interface {
	ExecuteQuery(context.Context, *QueryRequest) (*QueryResponse, error)
	mustEmbedUnimplementedSqlQueryServiceServer()
}

// UnimplementedSqlQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSqlQueryServiceServer struct{}

func (UnimplementedSqlQueryServiceServer) ExecuteQuery(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedSqlQueryServiceServer) mustEmbedUnimplementedSqlQueryServiceServer() {}
func (UnimplementedSqlQueryServiceServer) testEmbeddedByValue()                         {}

// UnsafeSqlQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SqlQueryServiceServer will
// result in compilation errors.
type UnsafeSqlQueryServiceServer interface {
	mustEmbedUnimplementedSqlQueryServiceServer()
}

func RegisterSqlQueryServiceServer(s grpc.ServiceRegistrar, srv SqlQueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedSqlQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SqlQueryService_ServiceDesc, srv)
}

func _SqlQueryService_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlQueryServiceServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SqlQueryService_ExecuteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlQueryServiceServer).ExecuteQuery(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SqlQueryService_ServiceDesc is the grpc.ServiceDesc for SqlQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SqlQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sqlquery.SqlQueryService",
	HandlerType: (*SqlQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteQuery",
			Handler:    _SqlQueryService_ExecuteQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sql_query.proto",
}
