swagger: "2.0"
info:
  title: ""
  version: ""
basePath: /
paths:
  /api_sql_query/{api_id}:
    post:
      operationId: QueryApiSql
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
